apiVersion: v1
kind: Service
metadata:
  name: {{ include "namel3ss-backend.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    app.kubernetes.io/name: {{ include "namel3ss-backend.name" . }}
